//Credit: This is originally from 
//  www.phenix.bnl.gov/WWW/p/draft/chiu/phenix/pad/getBadRoc.C
//
// Get the bad roc list from the calibration database for runno.
// This bad roc list is generated by OnlCal.
//
void getBadRoc(const int runno = 393483) {

  // Executing initialization macro
  //gROOT->Macro("loadDstLib.C");
  gSystem->Load("libfun4allfuncs.so");
  gSystem->Load("libpad.so");

  //cout << "testing,testing.." << endl;

  RunToTime *runtotime = RunToTime::instance();
  PHTimeStamp *TS = runtotime->getBeginTime(runno);

  PadCalibrationObject* PCO = new PadCalibrationObject();

  // for searching..
  // (year,month,day,hour,min,sec)
  //PHTimeStamp TS = PHTimeStamp(2009,4,12,8,0,0);
  PCO->setTimeStamp(*TS);
  PCO->FetchBadROCObjy();

  PCO->setDebugLevel(2);
  //PCO->print();
  TString name = "pad_deadroc_"; name += runno; name += ".dat";
  PCO->PutBadROCToFile( name );

  // Take out the garbage
  delete PCO;

  runtotime->DisconnectDB();
}
