#!/bin/csh

bsub root -l "SaveSingleCand.C(1)" 
bsub root -l "SaveSingleCand.C(2)"  
bsub root -l "SaveSingleCand.C(3)" 
bsub root -l "SaveSingleCand.C(4)" 
bsub root -l "SaveSingleCand.C(5)" 
bsub root -l "SaveSingleCand.C(6)" 
bsub root -l "SaveSingleCand.C(7)" 
bsub root -l "SaveSingleCand.C(8)" 
bsub root -l "SaveSingleCand.C(9)" 
bsub root -l "SaveSingleCand.C(10)" 

bsub root -l "SaveSingleCand.C(11)" 
bsub root -l "SaveSingleCand.C(12)" 
bsub root -l "SaveSingleCand.C(13)" 
bsub root -l "SaveSingleCand.C(14)" 
bsub root -l "SaveSingleCand.C(15)" 
bsub root -l "SaveSingleCand.C(16)" 
bsub root -l "SaveSingleCand.C(17)" 
bsub root -l "SaveSingleCand.C(18)" 
bsub root -l "SaveSingleCand.C(19)" 
bsub root -l "SaveSingleCand.C(20)" 

bsub root -l "SaveSingleCand.C(21)" 
bsub root -l "SaveSingleCand.C(22)" 
bsub root -l "SaveSingleCand.C(23)" 
bsub root -l "SaveSingleCand.C(24)" 
bsub root -l "SaveSingleCand.C(25)" 
bsub root -l "SaveSingleCand.C(26)" 
bsub root -l "SaveSingleCand.C(27)" 
bsub root -l "SaveSingleCand.C(28)" 
bsub root -l "SaveSingleCand.C(29)" 
bsub root -l "SaveSingleCand.C(30)" 

bsub root -l "SaveSingleCand.C(31)" 
bsub root -l "SaveSingleCand.C(32)" 
bsub root -l "SaveSingleCand.C(33)" 
bsub root -l "SaveSingleCand.C(34)" 
bsub root -l "SaveSingleCand.C(35)" 
bsub root -l "SaveSingleCand.C(36)" 
bsub root -l "SaveSingleCand.C(37)" 
bsub root -l "SaveSingleCand.C(38)" 
bsub root -l "SaveSingleCand.C(39)" 
bsub root -l "SaveSingleCand.C(40)" 

bsub root -l "SaveSingleCand.C(41)" 
bsub root -l "SaveSingleCand.C(42)" 
bsub root -l "SaveSingleCand.C(43)" 
bsub root -l "SaveSingleCand.C(44)" 
bsub root -l "SaveSingleCand.C(45)" 
bsub root -l "SaveSingleCand.C(46)" 
bsub root -l "SaveSingleCand.C(47)" 
bsub root -l "SaveSingleCand.C(48)" 
bsub root -l "SaveSingleCand.C(49)" 
bsub root -l "SaveSingleCand.C(50)" 

bsub root -l "SaveSingleCand.C(51)" 
bsub root -l "SaveSingleCand.C(52)" 
bsub root -l "SaveSingleCand.C(53)" 
bsub root -l "SaveSingleCand.C(54)" 
bsub root -l "SaveSingleCand.C(55)" 
bsub root -l "SaveSingleCand.C(56)" 
bsub root -l "SaveSingleCand.C(57)" 
bsub root -l "SaveSingleCand.C(58)" 
bsub root -l "SaveSingleCand.C(59)" 
bsub root -l "SaveSingleCand.C(60)" 
