@c This file is meant to be included other texinfo file
@c rarArgusBG configs
@c $Id: rarArgusBGConfig.texinfo,v 1.2 2007/06/29 08:37:50 zhanglei Exp $


@cindex rarArgusBG Configs
@cindex configuration, rarArgusBG
@cindex pdf configuration, rarArgusBG
@node rarArgusBGConfig
@subsection rarArgusBG Configs

@t{rarArgusBG} is a wrapper of @t{RooArgusBG} to build ArgusBG PDF.

@itemize @bullet
@cindex configStr, rarArgusBG config
@item @t{configStr = ArgusBG ["<pdf Title>"]}@*
This config specifies the pdf type is @t{ArgusBG}.
This config is required to have this pdf configured as @t{rarArgusBG}.

@cindex x, rarArgusBG config
@item @t{x = AbsReal Def}
@cindex max, rarArgusBG config
@item @t{max = AbsReal Def}
@cindex c, rarArgusBG config
@item @t{c = AbsReal Def}
@cindex pow, rarArgusBG config
@item @t{pow = AbsReal Def}@*
@t{x} is the default observable of the pdf.
@t{max} is the end point of the pdf, usually a constant.
@t{c} is the slope parameter of the pdf.
@t{pow} is the power of the multiplying term (normally 1/2).
@c
All the variables can be defined as @t{RooRealVar} or @t{RooFormulaVar}.
See @uref{#item_createVar, createVar} for more info on
how to create those variables.

@end itemize

@cindex example, rarArgusBG
@cindex example, ArgusBG
An example is shown below:
@example
[mesBkg Config]
fitData = desbData
configStr = ArgusBG
x = mes
max = 5.29 C
c = -20 L(-80 - -.1)
pow = 0.5 L(-3 - 3)
postPdfFloat = c
@end example
